---
- name: Download nodejs package
  shell: curl -fsSL https://rpm.nodesource.com/setup_14.x | sudo bash -

- name: Install nodejs
  yum:
    name: nodejs
    state: present

- name: Download yarn package
  shell: curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo

- name: Install yarn package
  yum: 
    name: yarn
    state: present