---
- name: Install dependencies for ruby-build
  yum: 
    name:
      - gcc-c++
      - make
      - patch
      - libyaml-devel
      - openssl-devel
      - zlib-devel
      - readline-devel
      - mysql-devel
    state: latest

- name: check rbenv install
  command: "{{ rbenv_path }}/bin/rbenv --version"
  register: rbenv_exists
  changed_when: False
  ignore_errors: True

- name: Install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: {{ rbenv_path }}
  when: rbenv_exists is failed

- name: Add ~.rbenv/bin to PATH
  blockinfile: 
    path: ~/.bashrc
    insertafter: EOF
    marker: "###<!-- {mark} ANSIBLE MANAGED BLOCK -->###"
    block: |
      export PATH="{{ rbenv_path }}/bin:${PATH}"
      eval "$(rbenv init -)"
  when: rbenv_exists is failed

- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
  when: rbenv_exists is failed

- name: Install ruby
  shell: bash -lc "rbenv install {{ruby_version}}"
  when: rbenv_exists is failed

- name: Set default ruby version
  shell: bash -lc "rbenv global {{ruby_version}} && rbenv rehash"
  when: rbenv_exists is failed
  
- name: Check version ruby version
  shell: bash -lc "ruby -v"
  register: ruby_check_default
  changed_when: False
  ignore_errors: yes
